version: '3.7'
services:
    webserver:
        build: .
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - _AIRFLOW_WWW_USER_CREATE="true"
            - _AIRFLOW_WWW_USER_USERNAME="admin"
            - _AIRFLOW_WWW_USER_PASSWORD="admin"
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN_SECRET="12345"
            - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth
        user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"

        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
                - ./airflow/dags:/usr/local/airflow/dags
                - ./airflow/dbt:/usr/local/airflow/dbt
                  #    - ./airflow/logs:/usr/local/airflow/logs
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "5000:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
